# Generated by Django 5.2.5 on 2025-10-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_intranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(blank=True, help_text='Hex (#3A8DFF)', max_length=7, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(blank=True, db_column='id_tipoc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.tipocalendario')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.usuario')),
            ],
            options={
                'db_table': 'evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_intranet.usuario')),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
        ),
    ]
