# Generated by Django 5.2.7 on 2025-11-28 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cargo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id_estados', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_solicitud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'db_table': 'rol_usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoCalendario',
            fields=[
                ('id_tipoc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_calendario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_solicitud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('id_cargo', models.ForeignKey(blank=True, db_column='id_cargo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.cargo')),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.departamento')),
                ('id_rol', models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.rolusuario')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('dia_inicio', models.DateField(blank=True, null=True)),
                ('dia_fin', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('aprobacion_jefe', models.BooleanField(blank=True, null=True)),
                ('aprobacion_director', models.BooleanField(blank=True, null=True)),
                ('estado_solicitud', models.ForeignKey(blank=True, db_column='estado_solicitud', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.estadosolicitud')),
                ('tipo_solicitud', models.ForeignKey(blank=True, db_column='tipo_solicitud', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.tiposolicitud')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.usuario')),
            ],
            options={
                'db_table': 'solicitud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_intranet.usuario')),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('cuerpo', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('leido', models.IntegerField(blank=True, null=True)),
                ('id_destinatario', models.ForeignKey(blank=True, db_column='id_destinatario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mensajes_id_destinatario_set', to='api_intranet.usuario')),
                ('id_remitente', models.ForeignKey(blank=True, db_column='id_remitente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.usuario')),
            ],
            options={
                'db_table': 'mensajes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id_licencia', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.FileField(upload_to='licencias/')),
                ('dia_inicio', models.DateField(blank=True, null=True)),
                ('dia_fin', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.usuario')),
            ],
            options={
                'db_table': 'licencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InicioRegistrado',
            fields=[
                ('id_inicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.usuario')),
            ],
            options={
                'db_table': 'inicio_registrado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_intranet.usuario')),
            ],
            options={
                'db_table': 'api_intranet_documento',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='jefe_departamento',
            field=models.ForeignKey(blank=True, db_column='jefe_departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.usuario'),
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id_calendario', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, help_text='Color en formato Hex (#3A8DFF)', max_length=7, null=True)),
                ('todo_el_dia', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_tipoc', models.ForeignKey(blank=True, db_column='id_tipoc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.tipocalendario')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.usuario')),
            ],
            options={
                'db_table': 'calendario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id_aviso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_intranet.usuario')),
            ],
            options={
                'db_table': 'avisos',
                'managed': True,
            },
        ),
    ]
