# Generated by Django 5.2.7 on 2025-12-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='perfiles/'),
        ),
    ]
