# Generated by Django 5.2.7 on 2025-12-14 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_intranet', '0002_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'managed': True, 'ordering': ['fecha', 'hora_inicio']},
        ),
        migrations.AddField(
            model_name='calendario',
            name='es_general',
            field=models.BooleanField(db_column='es_general', default=False),
        ),
        migrations.AddField(
            model_name='calendario',
            name='ubicacion',
            field=models.CharField(blank=True, db_column='ubicacion', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='id_tipoc',
            field=models.ForeignKey(blank=True, db_column='id_tipoc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_intranet.tipocalendario'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_intranet.usuario'),
        ),
    ]
