# Generated by Django 5.2.7 on 2025-11-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_intranet', '0003_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='aprobacion_director',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='aprobacion_jefe',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
