# Generated by Django 5.2.7 on 2025-12-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_intranet', '0003_alter_calendario_options_calendario_es_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dias_admin_asignados',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dias_permiso_asignados',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dias_vacaciones_asignados',
            field=models.IntegerField(default=15),
        ),
    ]
